### ISSUE TITLE
Set ip colocation limit to 100 on deploying 0.24 of nwaku 

### ISSUE THREAD

**Issue by chaitanyaprem** [status-im/infra-shards#27]
We have noticed that status-mobile CI is running into issues due to the fleet disconnecting the test emulators due to reaching IP colocation limit of 5 set in nwaku by default.  

Ref issue and discussion: https://github.com/status-im/status-go/issues/4459#issuecomment-1893319128

This has been made configurable in the 0.24 release of nwaku which is scheduled to be available on 22nd-Jan and can be applied on the shards.test fleet in order to avoid these peer disconnections. 

As part of this release, a new flag `ip-colocation-limit` is provided which has to be set to be `100`. 
This will ensure that CI would not face peer disconnections.

Ref nwaku issue: https://github.com/waku-org/nwaku/pull/2323

**Comment by pavloburykh** [comment]
Hi @chaitanyaprem!

Just confirming, is the 0.24 release of nwaku already accessible? If it is, then we can proceed with the task.  

@yakimant, In Jakub's absence this week (as per BambooHR), could I kindly ask you to review this task when you have a chance? Thank you!

**Comment by chaitanyaprem** [comment]
> Hi @chaitanyaprem!
> 
> Just confirming, is the 0.24 release of nwaku already accessible? If it is, then we can proceed with the task.
> 
> @yakimant, In Jakub's absence this week (as per BambooHR), could I kindly ask you to review this task when you have a chance? Thank you!

It was supposed to be released yesterday, but looks like it is not yet done. 
The nwaku team is validating the release candidate and once they are done with the release, then we can update the fleet.

**Comment by pavloburykh** [comment]
Hi @yakimant! nwaku 0.24 has been released https://github.com/waku-org/nwaku/releases/tag/v0.24.0 Could you please prioritise addressing the current issue when you have the opportunity? Thank you!

**Comment by yakimant** [comment]
Updating fleet images to 0.24.0:
https://ci.infra.status.im/job/nim-waku/job/deploy-shards-test/158/

**Comment by yakimant** [comment]
nim-waku role PR: https://github.com/status-im/infra-role-nim-waku/pull/24
